Bash is much powerful than sh

diff --git a/Linux/reconnect b/Linux/reconnect
--- a/Linux/reconnect
+++ b/Linux/reconnect
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 while true; do
   sleep 20s
@@ -12,11 +12,14 @@ while true; do
     fi
   fi
 
-  if [[! systemctl is-active teamviewerd.service >/dev/null 2>&1]] && [[$(command -v teamviewer)]]; then
-    systemctl restart teamviewerd.service
-    echo $(date +"%m/%d/%Y %I:%M:%p") "teamviewer" >> /home/Reconnect.log
-    if [ $(cat /home/Reconnect.log | wc -l) -gt 20 ]; then
-      sed -i '1d' /home/Reconnect.log
+  if [[ $(command -v teamviewer) ]]; then
+    systemctl is-active teamviewerd.service >/dev/null 2>&1
+    if [[ $? != 0 ]]; then # if exit code is not zero, restart
+      systemctl restart teamviewerd.service
+      echo $(date +"%m/%d/%Y %I:%M:%p") "teamviewer" >> /home/Reconnect.log
+      if [ $(cat /home/Reconnect.log | wc -l) -gt 20 ]; then
+        sed -i '1d' /home/Reconnect.log
+      fi
     fi
   fi
 done
